###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: php-starter-kit-redis

    mariadb:
      image: mariadb:10.4
      container_name: php-starter-kit-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=1010
        - MYSQL_DATABASE=square
        - MYSQL_USER=bora
        - MYSQL_PASSWORD=1010
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: php-starter-kit-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-starter-kit-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

